### ISSUE TITLE
Glow transform functions drop supplemental columns.

### ISSUE THREAD

**Issue by emaxwell** [projectglow/glow#108]
Currently, transform functions like 'normalize_variants' drop data in columns that are not part of the core VCF/BGEN schema by setting the values to null. Only columns of strings having the "INFO_" prefix are maintained if they are not part of the core schema. It would be ideal if Glow transformers could maintain these supplemental columns from the input DataFrame.

**Comment by kianfar77** [comment]
Resolved by #146
