### ISSUE TITLE
Support Scala 2.12

### ISSUE THREAD

**Issue by hammer** [projectglow/glow#117]
Spark has had [2.12 support](https://issues.apache.org/jira/browse/SPARK-14220) for over a year; what's blocking Glow from also supporting 2.12?

**Comment by henrydavidge** [comment]
Nothing blocking it, just don't have it yet. We'll certainly add 2.12 in advance of Spark 3.0 and would happily take a contribution sooner.

**Comment by henrydavidge** [comment]
There's a 2.12 artifact in the 0.3.0 release. Closing.
