### ISSUE TITLE
Missing steps in sample QC demo notebook

### ISSUE THREAD

**Issue by eric-czech** [projectglow/glow#132]
Hi, in the [sample-qc-demo](https://glow.readthedocs.io/en/latest/_static/notebooks/etl/sample-qc-demo.html) notebook, are there steps missing between the "Build map of sampleId -> QC stats" cell and the "Show per-sample QC metrics" cell?

I don't think ```display(qc.selectExpr("explode(qc) as (sampleId, per_sample_qc)").selectExpr("sampleId", "expand_struct(per_sample_qc)"))``` is possible otherwise (at least not with Glow 0.2.0 and Spark 2.4.4).

**Comment by karenfeng** [comment]
Thanks for the catch @eric-czech! I addressed this in https://github.com/projectglow/glow/pull/136.
