### ISSUE TITLE
Bug in VCF reader: Wrong start position

### ISSUE THREAD

**Issue by Hoeze** [projectglow/glow#138]
Hi, I'm failing to work with glow because it reports some variants at the wrong positions:
![image](https://user-images.githubusercontent.com/1200058/72903717-0af77180-3d2e-11ea-9dbe-8a7124da7200.png)
It's a SNP, so its start position should be `12513180` instead of `12513179`:
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER
X	12513180	X_12513180_G_A_b37	G	A	4027.47	PASS
```

Below is a MCVE. 
[I attached the corresponding test.vcf file.](https://github.com/projectglow/glow/files/4097841/test.vcf.zip)

```python3
import pyspark
from pyspark.sql import SparkSession
import glow
import os
import pandas as pd

import pyspark.sql.functions as f

os.environ['PYSPARK_SUBMIT_ARGS'] = " ".join([
    "--packages io.projectglow:glow_2.11:0.2.0,org.bdgenomics.adam:adam-assembly-spark2_2.12:0.29.0,io.delta:delta-core_2.11:0.4.0",
    "--driver-memory %sk" % MEM,
    "--executor-memory %sk" % MEM,
    "pyspark-shell"
])
os.environ['PYSPARK_SUBMIT_ARGS']

## define custom display Head to simplify looking at spark DataFrames.
def displayHead(df, nrows = 5):
    return df.limit(nrows).toPandas()

spark = (
    SparkSession.builder
    .appName('abc')
    .config("spark.local.dir", os.environ.get("TMP"))
    .config("spark.sql.execution.arrow.enabled", "true")
    .config("spark.sql.shuffle.partitions", "2001")
    .config("spark.driver.maxResultSize", "48G")
    .config("spark.databricks.io.cache.enabled", "true")
    .config("spark.databricks.io.cache.maxDiskUsage", "50G")
    .getOrCreate()
)
glow.register(spark)

df = (
    spark
    .read
    .format('vcf')
    .option("includeSampleIds", True)
    .load(os.path.expanduser("~/test.vcf"))
    .drop("names")
)

displayHead(df)
```

**Comment by Hoeze** [comment]
My query command for obtaining the single file was `bcftools view full_file.vcf.gz --regions X:12513180-12513180`

**Comment by karenfeng** [comment]
Hi @Hoeze, the VCF reader uses the 0-start, half-open (zero-based) coordinate system (see the [docs](https://glow.readthedocs.io/en/latest/etl/variant-data.html#vcf)). To convert to the 1-start, fully-closed system, you can add 1 to the start position.

**Comment by Hoeze** [comment]
@karenfeng Thank you so much for the explanation!
I was super confused, because all my VCF-transformer results had the correct 1-start results but joining them with my dataset resulted in nearly empty datasets.
