### ISSUE TITLE
Hello, there was an exception during the installation

### ISSUE THREAD

**Issue by lsygxw** [projectglow/glow#196]
When running the glow. Register (spark) command, the following exception occurs 
`File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/glow/glow.py", line 53, in register
    session._jvm.io.projectglow.Glow.register(session._jsparkSession)
  File "/usr/local/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/usr/local/spark/python/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/usr/local/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling z:io.projectglow.Glow.register.
: java.lang.NoSuchMethodError: scala.Function1.$init$(Lscala/Function1;)V` ；
Running environment: python3.7 python- PIP spark-2.4.5 

Do not know where the configuration of the wrong cause not to start up for the boss to solve

**Comment by henrydavidge** [comment]
It looks like you might be installing the library for the wrong scala version. You need to install the maven artifact that matches the scala version of your spark installation.

**Comment by lsygxw** [comment]
> It looks like you might be installing the library for the wrong scala version. You need to install the maven artifact that matches the scala version of your spark installation.
