### ISSUE TITLE
Hello, there is a problem with starting pyspark

### ISSUE THREAD

**Issue by lsygxw** [projectglow/glow#203]
The current environment: 
`ubuntu 18.4/spark-2.4.5/python3.7.5/scala-2.11.12/OpenJDK 64-Bit Server VM, Java 1.8.0_252`
Spark-shell can use the glow component normally, but pyspark does `glow.register(spark)`
 throws the following exception 
`File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/glow/glow.py", line 53, in register
    session._jvm.io.projectglow.Glow.register(session._jsparkSession)
  File "/usr/local/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/usr/local/spark/python/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/usr/local/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling z:io.projectglow.Glow.register.
: java.lang.NoSuchMethodError: scala.Function1.$init$(Lscala/Function1;)V
	at io.projectglow.sql.GlowSQLExtensions.<init>(SqlExtensionProvider.scala:39)
	at io.projectglow.GlowBase.register(Glow.scala:39)
	at io.projectglow.Glow.register(Glow.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)`
 I mentioned an issue yesterday, and your answer may be maven or scala version. However, I used the bin package of spark, and the scala version also conforms to the scala-2.11.12 version written on your `build.stb`. I sincerely hope that god can help me solve this problem

**Comment by henrydavidge** [comment]
Are you sure that you're launching the pyspark shell from the binary distribution with scala 2.11? Maybe you're launching a pip or conda installed version? I'm pretty sure that your error is caused by a scala version mismatch.

**Comment by lsygxw** [comment]
@henrydavidge  I'm sure the scala version I'm using is 2.11.12, which comes with sprak-bin. Spark-shell startup glow is normal and only pyspark can report an error. The spark-shell startup interface is as follows:
![image](https://user-images.githubusercontent.com/38533349/81041899-834f0080-8ee1-11ea-930c-6002c7201483.png)

**Comment by henrydavidge** [comment]
@lsygxw Yep, the fact that you only get an error when using pyspark makes me think that the pyspark shell corresponds to a different spark installation with the wrong scala version.

Try running these commands in the pyspark shell:
```python
>>> spark._jvm.scala.util.Properties.versionString()
>>> spark._jvm.scala.util.Properties.javaVersion()
```

**Comment by lsygxw** [comment]
@henrydavidge  First of all, thank you for your help. The result is as follows after executing in pyspark according to your method:
![image](https://user-images.githubusercontent.com/38533349/81131612-4edd5200-8f7e-11ea-874d-395453ecf40c.png)
Are the results as expected?

**Comment by henrydavidge** [comment]
Hm, that does look like the right scala and java version. How exactly are you installing glow?

**Comment by lsygxw** [comment]
@henrydavidge  Same as the demo on your document `pip3 install glow.py`  
Is it possible to lack some dependency or configuration? My 'spark-env.sh' configuration is as follows:
![image](https://user-images.githubusercontent.com/38533349/81140476-0fbdf980-8f9c-11ea-9485-1398e468b9f4.png)

**Comment by magelan** [comment]
I get the same error with the versions below.

     ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 2.4.3
      /_/

Using Python version 3.6.9 (default, Apr 18 2020 01:56:04)
SparkSession available as 'spark'.
>>> spark._jvm.scala.util.Properties.versionString()
'version 2.11.12'
>>> spark._jvm.scala.util.Properties.javaVersion()
'1.8.0-adoptopenjdk'

**Comment by magelan** [comment]
In my case the problem was that I used the dowloaded glow jar file instead of the --packages option because of a corporate proxy. That did not load the dependencies and caused problems.

this was required to get proxy and certificates working:
pyspark  --conf "spark.driver.extraJavaOptions=-Djava.net.useSystemProxies=true -Djavax.net.ssl.trustStore=keystore.jks" --packages io.projectglow:glow_2.11:0.4.0

**Comment by henrydavidge** [comment]
I'm tentatively going to close. @lsygxw feel free to reopen if your issue persists.
