### ISSUE TITLE
v0.6.x Release Date

### ISSUE THREAD

**Issue by eric-czech** [projectglow/glow#256]
Will you guys be pushing a v0.6 release soon?  It would be great to be able to use the functions in the [examples for WGR](https://glow.readthedocs.io/en/latest/tertiary/whole-genome-regression.html#) (at least reshape_for_gwas and transform_loco) that don't exist in the latest packaged release on pypi (v0.5.0).

**Comment by karenfeng** [comment]
Hi @eric-czech! Thanks for the feedback, we plan on releasing v0.6 once logistic regression (https://github.com/projectglow/glow/pull/245) is merged.

**Comment by eric-czech** [comment]
I see, thanks @karenfeng.
