### ISSUE TITLE
WGR incorrect default alphas in RidgeRegression

### ISSUE THREAD

**Issue by eric-czech** [projectglow/glow#260]
In the second stage regression for WGR, the default alphas generated here based on the number of distinct headers are including the `label` values:

https://github.com/projectglow/glow/blob/f3edf5bb8fe9c2d2e1a374d4402032ba5ce08e29/python/glow/wgr/linear_model/ridge_model.py#L220

This means that the alphas become a function of the number of outcomes (i.e. labels), which I assume isn't what was intended right?  It seems odd to me that the results would change for one outcome if it was fit alone vs w/ others, so I think it should probably only be based on the number of features for the regression like stage 1 -- number of variant blocks * number of stage 1 alphas (not then also * number of outcomes).

**Comment by LelandBarnard** [comment]
Hi Eric, great catch, I only recently noticed this as well  It is definitely unintended, we will fix it in an upcoming release.

**Comment by henrydavidge** [comment]
This is resolved.
