### ISSUE TITLE
Improve GWAS functions in Glow

### ISSUE THREAD

**Issue by henrydavidge** [projectglow/glow#270]
- Report contingency table for binary traits
- Ensure that we're exposing all necessary association test result statistics
- Performance optimization, particularly for multiple phenotypes

**Comment by ptn24** [comment]
@henrydavidge , would be great if the model training/fitting metrics could be reported after the fact. E.g., https://github.com/projectglow/glow/blob/1ca02f5171ba1c3fc120ab80c7d1663ed77d5d86/core/src/main/scala/io/projectglow/sql/expressions/FirthTest.scala#L89 and https://github.com/projectglow/glow/blob/1ca02f5171ba1c3fc120ab80c7d1663ed77d5d86/core/src/main/scala/io/projectglow/sql/expressions/LogisticRegressionGwas.scala#L73. Would be useful for troubleshooting NaN field values. Relatedly, would it be reasonable to let users configure the max num iterations?

**Comment by henrydavidge** [comment]
@ptn24 FYI, we're releasing a new version of Glow in a few days that will include a specific status column and allow you to configure the max iterations.

**Comment by ptn24** [comment]
Great, thank you!
