### ISSUE TITLE
bigvcf writer creates header only output

### ISSUE THREAD

**Issue by magelan** [projectglow/glow#272]
I merged some vcfs and produced a df with content like this:

[Row(contigName='1', start=1557, referenceAllele='A', genotypes=[Row(sampleId='7WV160085_DH0003', calls=[0, 1]), Row(sampleId='7WV160085_DH0008', calls=[0, 1]), Row(sampleId='7WV160085_DH0025', calls=[0, 0])], alternateAlleles=['T'], end=None, refAllele='A'),
 Row(contigName='1', start=1734, referenceAllele='C', genotypes=[Row(sampleId='7WV160085_DH0003', calls=[0, 1]), Row(sampleId='7WV160085_DH0008', calls=[0, 0]), Row(sampleId='7WV160085_DH0025', calls=[0, 0])], alternateAlleles=['CA'], end=None, refAllele='C')]

Looks ok to me, but trying to save it as bigvcf results in an empty file with partial headers.

.write.format("bigvcf").save("data_test/gvcf_sample_start_less2000")

.write.format("vcf").save("data_test/gvcf_sample_start_less2000") throws a error about empty partitions

**Comment by magelan** [comment]
Schema:

root
 |-- contigName: string (nullable = true)
 |-- start: long (nullable = true)
 |-- referenceAllele: string (nullable = true)
 |-- genotypes: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- sampleId: string (nullable = true)
 |    |    |-- calls: array (nullable = true)
 |    |    |    |-- element: long (containsNull = true)
 |-- alternateAlleles: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- end: null (nullable = true)
 |-- refAllele: string (nullable = true)

**Comment by karenfeng** [comment]
Hi @magelan, it looks like your DataFrame is malformed in two key ways. The `end` field cannot be NullType; it should be LongType and contain a numeric value. In addition, the elements in the `genotypes.call` field should not be LongType, they should be IntegerType. We also do not require the `refAllele` field, as the reference alleles are expected in the `referenceAllele` field. How did you generate this DataFrame?

**Comment by karenfeng** [comment]
I would recommend you set the validation stringency during the VCF write step if you're seeing dropped rows.
`df.write.format("bigvcf").option("validationStringency", "STRICT").save(output)` will throw an exception upon encountering a malformed row. When I set this for the provided DataFrame, the exception reflects that the `end` field was not set and the resulting VariantContext could not be built and written to VCF:
```
java.lang.IllegalArgumentException: Could not build variant context: BUG: GenomeLoc 1:1558--1 has a size == -1558 but the variation reference allele has length 1 this = [VC Unknown @ 1:1558--1 Q. of type=SNP alleles=[A*, T] attr={} GT=[[7WV160085_DH0003 A*/T],[7WV160085_DH0008 A*/T],[7WV160085_DH0025 A*/A*]] filters=
```
Alternately, setting the validation stringency to `LENIENT` will drop malformed rows while logging errors.
By default, we silently drop malformed rows. I'll add documentation to reflect this.

**Comment by magelan** [comment]
Hi Karen,

we kind of met at a glow workshop, a few wekks ago :-)
I got it running thanks to your help. The dataframe comes from trying to merge a few vcfs. I loaded a folder with a bunch of vcfs, or gvcfs to be exact, called with the same reference.
Then this code:


altAll= dft.where((dft.genotypes[0].calls[0]>0) |( dft.genotypes[0].calls[1]>0)).where(dft.genotypes[0].conditionalQuality>30)\
.select(dft.contigName, dft.genotypes[0].sampleId.alias("sample"),"genotypes",dft.start,dft.referenceAllele, dft.alternateAlleles, dft.genotypes[0].conditionalQuality.alias("conditionalQuality"),dft.genotypes[0].calls, coalesce(dft.alternateAlleles[(dft.genotypes[0].calls[0])-1],dft.referenceAllele ).alias("call_0"), coalesce(dft.alternateAlleles[(dft.genotypes[0].calls[1])-1],dft.referenceAllele ).alias("call_1"))\
.groupBy("contigName","start","referenceAllele").agg(collect_set("call_0").alias('y'),collect_set("call_1").alias('x'),collect_set("referenceAllele").alias('ref'))\
.withColumn('alternateAlleles2', array_except(array_distinct(concat('y',"x" )), "ref" )).select("contigName","start",col("alternateAlleles2").alias("alternateAlleles"))



dft.withColumn("x", coalesce(dft.alternateAlleles[(dft.genotypes[0].calls[0])-1],dft.referenceAllele ))\
.withColumn("y", coalesce(dft.alternateAlleles[(dft.genotypes[0].calls[1])-1], dft.referenceAllele ))\
.select("contigName","start", "end",dft.genotypes[0].sampleId.alias("sampleId"),"x", "y")\
.join(altAll, ["contigName", "start"] )\
.withColumn("calls", array(expr("int(array_position(alternateAlleles,x))"),expr("int(array_position(alternateAlleles,y))")))\
.join(pos_sample, ["contigName", "start", "sampleId" ],how='right' ).orderBy("start")\
.withColumn("calls", when(col('calls').isNull(), array([lit(0)]*2)).otherwise(col('calls')))\
.groupBy("contigName", "start","referenceAllele")\
  .agg(collect_list(struct("sampleId", "calls")).alias("genotypes")).orderBy("contigName","start")\
.withColumn("genotypes", sort_array(col("genotypes")))\
.join(altAll, ["contigName", "start"] ).withColumn("end", col("start")+length(col('referenceAllele')))\
.write.format("bigvcf").option("validationStringency", "STRICT").save("data_test/gvcf_sample_start_less2000_val2")

I now get what I expected:


##fileformat=VCFv4.2
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  7WV160085_DH0003        7WV160085_DH0008        7WV160085_DH0025
1       1558    .       A       T       .       .       .       GT      0/1     0/1     0/0
1       1735    .       C       CA      .       .       .       GT      0/1     0/0     0/0

Strangely the end positions appear, instead of the start positions I expected. This time I used the start position plus the length of the ref as the end. Maybe that is not sound in the vcf context. 

It might be what issue #183 asks for. Posted the old code there as well.

**Comment by magelan** [comment]
If I do not filter on a small region, as I did for testing, I get a new error:

java.lang.IllegalArgumentException: Could not build variant context: Duplicate allele added to VariantContext: T

How can I get the row that caused this error for debugging or what does it mean?
Or how can I assure that the dataframe can be written as a vcf?

**Comment by karenfeng** [comment]
Hi @magelan, are the VCFs arising from array data? If so, I would recommend using the aggregation logic described in our documentation: https://glow.readthedocs.io/en/latest/etl/merge.html. This may not suffice for your use case - for gVCFs, you likely want to perform joint genotyping instead of a simple merge.

**Comment by magelan** [comment]
Hi Karen,

yes, I basically tried to implement a Joint genotyping of gvcfs in pyspark. In the fisrt step ignoring all qualities and likelyhoods. Found out it's not so simple, but still think it should be. :-) Will do a run with the databricks pipeline.
Guess it might work with gvcfs that are not aggreagted into blocks. 

Regarding the simple merge you linked I have one question.  Shouldn't the alternateAlleles also be aggregated, instead of being in the group by?
If there are several different alleles the result would be mulitiple lines for the same position. Might be technically ok, e.g. valid vcf, but not what I'd expect.

**Comment by williambrandler** [comment]
Hi @magelan, thanks for this. Yes, joint-variant calling is the best practice for merging gVCFs

you can either run the GATK's [GenotypeGCVFs](https://gatk.broadinstitute.org/hc/en-us/articles/360036899732-GenotypeGVCFs) on a single node. Or use [Databricks](https://docs.databricks.com/applications/genomics/tertiary/joint-genotyping-pipeline.html)' spark-based implementation of GenotypeGCVFs

As for the simple merge, this is only for array data where we assume all variants are biallelics. For NGS data please use joint-genotyping to merge!

**Comment by henrydavidge** [comment]
@magelan closing this out. Feel free to reopen if you have specific followups.
