### ISSUE TITLE
Revise API of WGR LogisticRegression transform and transform_loco 

### ISSUE THREAD

**Issue by kianfar77** [projectglow/glow#288]
As discussed with @LelandBarnard, currently the APIs of `LogisticRegression.transform` and `LogisticRegression.transform_loco` allow for passing covariates as an argument. This is while covariates are not required in the logic as currently recommended because only X*B is calculated by these transforms. Passing any covariate to these functions causes a runtime error due to mismatch of matrix dimensions during multiplication.

**Comment by henrydavidge** [comment]
This has been fixed!
