### ISSUE TITLE
Gene based tests

### ISSUE THREAD

**Issue by jjfarrell** [projectglow/glow#308]
Are there any plans to implement gene  based tests for Glow such as Skat, Skat-o, SAIGE-gene?

**Comment by williambrandler** [comment]
no plans, the data volume is small enough where the complexity and overhead of distributing across multiple nodes is not warranted at this stage!
These tools are best run on a single node.

**Comment by williambrandler** [comment]
I take back what I said previously, it is relatively straightforward for users to extend to gene burden tests, see,
https://github.com/projectglow/glow/issues/351
