### ISSUE TITLE
Reading UKBB bgen results in empty DataFrame

### ISSUE THREAD

**Issue by mRcSchwering** [projectglow/glow#325]
Hi, I am trying to use glow to read a bgen file.
Unfortunately, the resulting DataFrame is empty.

```
import glow
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("ukbbPart").getOrCreate()
glow.register(spark)

file_name = "file:///path/to/dir/file.bgen"
df = spark.read.format("bgen").load(file_name)

print(df.show())
```

Results in:

```
+----------+-----+---+-----+---------------+----------------+---------+
|contigName|start|end|names|referenceAllele|alternateAlleles|genotypes|
+----------+-----+---+-----+---------------+----------------+---------+
+----------+-----+---+-----+---------------+----------------+---------+
```

The file is from UKBB.
Reading it from an HPC using [bgenx](https://enkre.net/cgi-bin/code/bgen/wiki?name=bgenix)
confirms the file is not empty.
Environment:

```
[hadoop@ip-10-0-1-200 ~]$ pip freeze | grep pyspark
pyspark==3.0.1
python37-sagemaker-pyspark==1.4.1
[hadoop@ip-10-0-1-200 ~]$ pip freeze | grep glow
glow.py==0.6.0
[hadoop@ip-10-0-1-200 ~]$
```

**Comment by henrydavidge** [comment]
@mRcSchwering Does the BGEN file exist at that path on every node in your cluster? The `file:` scheme tells Spark / Glow to read from the local filesystem, which may not be what you want in this case.

**Comment by mRcSchwering** [comment]
ah no I thought it's only necessary on the master node.
Originally I tried it directly from S3 (`s3://`).
That also gave empty DataFrames.

**Comment by mRcSchwering** [comment]
ok I found the reason. My filename was starting with an underscore (`_004_ikbb_imp_chr1.bgen`). Renaming the file solved it (`004_ikbb_imp_chr1.bgen`). Apparently it's silently ignoring files that start with `_`.

**Comment by henrydavidge** [comment]
Ah yes, Spark (and Hadoop) treat files beginning with `_` as "hidden". Thanks for following up!

**Comment by mRcSchwering** [comment]
oh man, what a feature.... gave me several mental breakdowns
