### ISSUE TITLE
Py4JJavaError when initiating Glow

### ISSUE THREAD

**Issue by Biogitte** [projectglow/glow#340]
Hi Project Glow team,

The last few days, I have tried to get Glow to work without any luck. I continue to get the following error when running the `spark = glow.register(spark)` in Jupyter Notebook, according to the [guide](https://glow.readthedocs.io/en/latest/getting-started.html#). 

```
Py4JJavaError: An error occurred while calling z:io.projectglow.Glow.register.
: java.lang.NoClassDefFoundError: com/typesafe/scalalogging/LazyLogging
```

**System information:**
- macOS Big Sur (v. 11.1) 
- Python v. 3.8.6 
- Spark (v. 3.0.1) with a pre-built package for Apache Hadoop 3.2+
- PySpark v. 3.0.1
- Scala v. 2.13.4
- Glow v. 0.6.0
- Java 8 (adoptopenjdk-8.jdk)

**Have have been done?**
For all attempts, I am starting in a virtual environment where I source the following global_env.sh:

```
export SPARK_HOME=$HOME/tools/spark
export PATH=$SPARK_HOME/bin:$PATH
export PYSPARK_DRIVER_PYTHON=jupyter
export PYSPARK_DRIVER_PYTHON_OPTS='notebook'
export PYSPARK_PYTHON=python3
export JAVA_HOME='/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home'
```             

From there, I have tried (of what I can remember) that results in the error above:

1) Initiate PySpark as described in the [guide](https://glow.readthedocs.io/en/latest/getting-started.html#):       
    
 ```  
pyspark --packages io.projectglow:glow-spark3_2.12:1.0.0 --conf spark.hadoop.io.compression.codecs=io.projectglow.sql.util.BGZFCodec                                                     
 ```  

2) Initiate PySpark with, what seems like an other package from the [Maven Repo](https://mvnrepository.com/artifact/io.projectglow/glow-spark3_2.12/0.6.0)

 ```  
pyspark --packages io.projectglow:glow-spark3_2.12:0.6.0 --conf spark.hadoop.io.compression.codecs=io.projectglow.sql.util.BGZFCodec
```  

3) Initiate Pyspark as suggested in [issue 203](https://github.com/projectglow/glow/issues/203) to get proxy and certificates working:

 ```  
pyspark --conf "spark.driver.extraJavaOptions=-Djava.net.useSystemProxies=true -Djavax.net.ssl.trustStore=keystore.jks" --packages io.projectglow:glow_2.11:0.4.0
 ```  

 4) And with the, what seems at the other package, from Maven Repo (see 2))

 ```  
pyspark --conf "spark.driver.extraJavaOptions=-Djava.net.useSystemProxies=true -Djavax.net.ssl.trustStore=keystore.jks" --packages io.projectglow:glow-spark3_2.12:0.6.0
 ``` 

5) And have tried to specify the Spark session inside Jupyter Notebook (with many different conf options) - and just initiated Spark in Jupyter Notebook with  `pyspark ` in the terminal

 ``` 
import pyspark
import glow
from pyspark.sql import SparkSession

spark = SparkSession.builder\
    .appName('GlowingSpark')\
    .master('local[*]')\
    .config('spark.driver.memory','2G')\
    .config('spark.driver.maxResultSize', '1G') \
    .config('spark.jars.packages', 'com.typesafe.scala-logging:scala-logging-slf4j_2.11:jar:2.1.2')\
    .config('spark.jars.packages', 'io.projectglow:glow-spark3_2.12:jar:0.6.0')\
    .getOrCreate()

spark = glow.register(spark)
 ``` 

Can you help me get around this error? I am looking much forward to trying out your library! 

Thanks,

Best wishes, Birgitte

**Comment by karenfeng** [comment]
Hi @Biogitte! You caught us in an awkward position - v1.0.0 hasn't been released yet, so our docs are a bit ahead of ourselves, and `spark = glow.register(spark)` is specific to the new release 😅 We're in the process of cutting the releases to Maven and Pypi (and Conda) now.

Your primary problem is likely unrelated to this though - you seem to be mixing different versions of Scala. The `io.projectglow:glow-spark3_2.12` Maven artifact is for Scala 2.12.8 (to match the Spark 3.0.0 release), and you're on Scala 2.13. I would recommend downgrading to Scala 2.12 and trying again.

**Comment by Biogitte** [comment]
Hi @karenfeng,

It is not a bad thing being ahead of documentation :)

You're right - when I downgraded to Scala 2.12 (and set SPARK_LOCAL_IP=<my local IP>) it worked! Thanks!

Best wishes, Birgitte
