### ISSUE TITLE
Is GQ re-computed after splitting multi-allelic?

### ISSUE THREAD

**Issue by ConnorBarnhill** [projectglow/glow#355]
Looking at the [docs for splitting multiallelic variants](https://glow.readthedocs.io/en/latest/etl/variant-splitter.html), it looks like the answer is no. This differs from the hail implementation of "split_multi_hts". Should QC filters based on GQ be applied before splitting?

**Comment by kianfar77** [comment]
This does not happen currently following what [vt decompose](https://genome.sph.umich.edu/wiki/Vt#Decompose) does. It should be easy to add. Thanks for raising.
