### ISSUE TITLE
Best way to do a full outer join?

### ISSUE THREAD

**Issue by ConnorBarnhill** [projectglow/glow#357]
Not clear how to do this from the "Merging Variant Dataset" docs. Essentially, I have two sharded VCFs with different numbers of variants and samples. I think the example shown assumes the same set of variants in each VCF.

What is the best way to ensure that variants that exist in one VCF but not the other have a genotype record for every sample,  defaulting to NA/no call for samples in the other VCF?

**Comment by williambrandler** [comment]
Hey Connor, this is related to solving the n+1 problem in genomics using delta lake.

Best practice is to explode pVCFs to one sample one genotype per row. 
Split multiallelics, left normalize. Append them all into a Bronze Delta Lake Table.

Do a groupBy to get a table of unique variants. 
And use this to convert individual VCFs into "gVCFs", so each position has a genotype call. 
Append "gVCFs" into a silver delta table.
Then groupBy variant, collect_array on genotypes!

I have a couple of example notebooks for simulating gVCFs, could be adapted? Will need some work.

See [here](https://databricks-prod-cloudfront.cloud.databricks.com/public/4027ec902e239c93eaaa8714f173bcfc/8320872975591174/2068386856343846/7059035168435387/latest.html) and [here](https://databricks-prod-cloudfront.cloud.databricks.com/public/4027ec902e239c93eaaa8714f173bcfc/8320872975591174/2068386856343866/7059035168435387/latest.html)

What do you think?

**Comment by ConnorBarnhill** [comment]
Hi William,

Thanks for the response. That's what I figured, I wasn't sure if there was a better way to achieve this without exploding the genotypes field.

**Comment by williambrandler** [comment]
You're on the right track though, 

When working interactively on continually growing large datasets, 
there has to be a way to do joins, update statistics and filter down to something manageable for analytics.

The old school hypothesis-free genome-wide approach does not work on population scale data paired with real-world/clinical data!
