### ISSUE TITLE
[Glow 1.0.0] [regression] Undefined function: 'expand_struct'

### ISSUE THREAD

**Issue by dnafault** [projectglow/glow#362]
Seems 'expand_struct' [1] is undefined in Glow 1.0.0

```
    val df =
      spark
        .read
        .format("vcf")
        .option("includeSampleIds", "false")
        .option("flattenInfoFields", "true")
        .option("validationStringency", "lenient")
        .load(path)

    df
      .withColumn("VEP", expr("explode(INFO_CSQ)"))
      .selectExpr("contigName",
        "start",
        "referenceAllele",
        "alternateAlleles",
        "INFO_AN",
        "INFO_AC",
        "INFO_AF",
        "expand_struct(VEP)"
      )
```

throws exception:

```
Exception in thread "main" org.apache.spark.sql.AnalysisException: Undefined function: 'expand_struct'. This function is neither a registered temporary function nor a permanent function registered in the database 'default'.; line 1 pos 0
```

Worked well in 0.6.0. I haven't looked further, maybe something is missed on my side, but it seems like a regression in 1.0.0 and it breaks functionality.

[1] https://glow.readthedocs.io/en/latest/etl/utility-functions.html

**Comment by karenfeng** [comment]
Hi @dnafault! Can you let me know your full setup? In Glow v1.0.0, the default behavior of `Glow.register` is different (see https://github.com/projectglow/glow/pull/326) - it doesn't modify the existing Spark session.  It looks like you're using `spark` as the SparkSession, instead of a new Spark session.

**Comment by dnafault** [comment]
Ah, thank you Karen!

That explains the issue.

You are absolutely right, the code around spark session wasn't modified. In fact, none of the code was modified at all. The only change made was updating dependencies from 0.6.0 to 1.0.0.

I find the default behaviour in register to create a new session with `newSession: Boolean = true` to be quite unfortunate. It leaves all the existing code to stay unaware of the side effects of the changes and pass the compile time without any signs of those changes. Also, most of the functionality continues to work at runtime, so the issue stays unnoticed until some more exotic cases fail at runtime sometime later.

Either the `false` default value for the `newSession` (leaves all existing code working fine with all the session settings updated without any changes in existing code required) or removing the default value altogether (breaks existing code in compile time) would seem to be more appropriate.

As the last resort, when all things already released to the wild and it's too late to fix them, some warnings in release notes about hidden behaviour changes would be helpful =)

cheers,
dmitry

**Comment by karenfeng** [comment]
Thanks for the feedback Dmitry! @henrydavidge would have more context, but I believe we changed the default behavior to avoid some corner-case errors. As you noted, however, this would quietly break the upgrade to v1.0.0. I'll add a note to the v1.0.0 release notes that the behavior of `register` has changed.
