### ISSUE TITLE
Whole Genome Regression TypeError

### ISSUE THREAD

**Issue by ConnorBarnhill** [projectglow/glow#363]
After generating alphas at the ridge reduction step, throws the following error:
TypeError: type of the return value['alpha_0'] must be nptyping.types._number.Number; got numpy.float64 instead

### Libraries
glow.py==1.0.0 (PyPi)
io.projectglow:glow-spark3_2.12:1.0.0 (Maven)

**Comment by williambrandler** [comment]
hey @ConnorBarnhill could you share a sample notebook so we can take a look?

**Comment by williambrandler** [comment]
hey @ConnorBarnhill seems like this is related to an issue with the Glow docs not reflecting recent API changes
we're working on it here, https://github.com/projectglow/glow/pull/365

**Comment by ConnorBarnhill** [comment]
Thanks, I'll take a look. I also just sent you a link to a job run via email

![image](https://user-images.githubusercontent.com/7959016/115082513-a5ac1500-9ecb-11eb-9e80-301db7dbb30f.png)

**Comment by williambrandler** [comment]
quick update, we are still working on a fix for this and testing with another user

**Comment by ConnorBarnhill** [comment]
Thanks for the update!

**Comment by kianfar77** [comment]
This is now fixed at #366 and will be included in a new release shortly.

**Comment by ConnorBarnhill** [comment]
Great, thank you!
