### ISSUE TITLE
How to read tsv?

### ISSUE THREAD

**Issue by Hoeze** [projectglow/glow#368]
I'm trying to run:
```python
glow.transform(
    "pipe",
    input_df.limit(10),
    cmd=json.dumps(shlex.split(cmd)),
    inputFormatter='vcf',
    inVcfHeader='infer',
    outputFormatter='csv',
    out_delimiter="\t"
)
```
but I still only get a single column.
How can I read tsv output?

**Comment by karenfeng** [comment]
Hi @Hoeze! I just ran a quick test locally, and the CSV piper should still work for TSVs. However, the CSV datasource exposes many options, including whether there is a header (`out_header`) or there are comments (`out_comment`). Can you tell me more about what the command you're running?

**Comment by henrydavidge** [comment]
Closing since we now support only the text piper and to/from csv functions in Spark
