### ISSUE TITLE
netlib native dependency issue

### ISSUE THREAD

**Issue by jpdna** [projectglow/glow#37]
When I run:
```
pyspark --packages io.projectglow:glow_2.11:0.1.0
```
I get a dependency error:
```
py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
: java.io.FileNotFoundException: File file:/home/paschalj/.ivy2/jars/com.github.fommil.netlib_netlib-native_ref-osx-x86_64-1.1.jar does not exist
```
I attempted to compile Spark with the needed libraries:
```
mvn -Pyarn -Phadoop-2.7 -Pnetlib-lgpl -DskipTests clean package
```
as described here:
https://github.com/Mega-DatA-Lab/SpectralLDA-Spark/wiki/Compile-Spark-with-Native-BLAS-LAPACK-Support

but so far still get that error, though have not validated that those lose libraries are properly working with my Spark install.
I'm using Ubuntu 18.04
Any suggestions much appreciated!
Thanks!

**Comment by henrydavidge** [comment]
@jpdna Thanks for reporting! It looks like `spark-submit`'s Maven resolver doesn't choose the collect path for dependencies with a classifier.

As a workaround, you can manually exclude the netlib packages:

**Comment by henrydavidge** [comment]
@jpdna I'm going to close this issue. Please feel free to reopen if you have any further problems.
