### ISSUE TITLE
Release on Spark 3.1

### ISSUE THREAD

**Issue by karenfeng** [projectglow/glow#387]
Spark 3.1 was released on [March 2](https://spark.apache.org/releases/spark-release-3-1-1.html), we should rebase the glow-spark3 release to be on Spark 3.1 (currently on Spark 3.0).

**Comment by dberma15** [comment]
This would be helpful as I'm having some troubles with glow on later versions.

**Comment by williambrandler** [comment]
glow v1.1.0 has now been released, so closing this thread
