### ISSUE TITLE
Integrating glow into pipeline

### ISSUE THREAD

**Issue by linchihfan** [projectglow/glow#394]
Hi,

I'm fairly new to pyspark and glow. 
Is a way to start the spark and glow session in a python script instead of the python shell or jupyter notebook? Say if I want to integrate glow into my snakemake pipeline, how do I go about doing so? 
Any guidance will be much appreciated!

**Comment by williambrandler** [comment]
hey @clin113jhu, I have not used snakemake before so cannot give detailed guidance. But there is no reason why you cannot use it to orchestrate spark jobs. This is for example, what [pybda](https://pybda.readthedocs.io/en/latest/) does.

Other options include Apache Airflow or the Databricks Jobs API

**Comment by henrydavidge** [comment]
@linchihfan See the documentation at https://spark.apache.org/docs/latest/api/python/getting_started/quickstart_df.html. You can start a Spark session and then register Glow.
