### ISSUE TITLE
.bgz file load failure

### ISSUE THREAD

**Issue by olesya13** [projectglow/glow#397]
Hi,

I got a failure when trying to load .bgz file. Script below
```
import glow
glow.register(spark)
directory = "wasbs://gnomad@azureopendatastorage.blob.core.windows.net/release/2.1.1/vcf/exomes"
source = directory + "/gnomad.exomes.r2.1.1.sites.21.vcf.bgz"
data_spark = spark.read\
  .format("vcf")\
  .load(source)
```
fails with the following message 

> Job aborted due to stage failure: Task 7 in stage 0.0 failed 4 times, most recent failure: Lost task 7.3 in stage 0.0 (TID 10) (10.139.64.4 executor 0): htsjdk.tribble.TribbleException$InvalidHeader: Your input file has a malformed header: We never saw the required CHROM header line (starting with one #) for the input VCF file

but if I create a new session and register glow for the session (see script below) it works fine
```
import glow
glow.register(spark)
directory = "wasbs://gnomad@azureopendatastorage.blob.core.windows.net/release/2.1.1/vcf/exomes"
source = directory + "/gnomad.exomes.r2.1.1.sites.21.vcf.bgz"
sess = spark.newSession()
sessWithGlow = glow.register(sess)
data_sess = sessWithGlow.read\
  .format("vcf")\
  .load(source)
```

I use Azure Databricks runtime 8.1 (Apache spark 3.1.1, Scala 2.12) and io.projectglow:glow-spark3_2.12:1.0.1, data used in the scripts is public data.

I expected that `glow.register(spark)` should be enough to load data but looks like it's not a case for .bgz. Could you please clarify what the right way to load .bgz files?

**Comment by williambrandler** [comment]
Hey @olesya13 do you get the same issue if you use Databricks Runtime 7.3, v1.0.1 of glow has only been tested on Spark 3.0.0

The next version, Glow v1.1.0, will support Spark 3.1.x

**Comment by karenfeng** [comment]
By default, we no longer modify the Spark session in-place as of v1.0.0. If you run `spark = glow.register(spark)` as the registration step, this should resolve the issue.

**Comment by olesya13** [comment]
@williambrandler  and @karenfeng  thanks for your response!
`glow.register(spark)` doesn't work for Runtime 7.3, but `spark = glow.register(spark)` works for both 7.3 and 8.1.

**Comment by williambrandler** [comment]
Great!
