### ISSUE TITLE
Writing VCF with FloatType in INFO field fails

### ISSUE THREAD

**Issue by ConnorBarnhill** [projectglow/glow#404]
Trying to write a single VCF file (bigvcf) from a spark dataframe. I have an INFO field that's a float. Writing throws an error on the FloatType:

![image](https://user-images.githubusercontent.com/7959016/132544110-b3bfbaf0-be1f-44c9-ab79-2d614bb687ba.png)

**Comment by williambrandler** [comment]
what happens if you set the validation stringency to lenient?

**Comment by ConnorBarnhill** [comment]
Same result

**Comment by williambrandler** [comment]
Was this INFO field represented in the original VCF?
And has the schema changed for the INFO field?

**Comment by henrydavidge** [comment]
This should be resolved now
