### ISSUE TITLE
quarantine functionality in pipe transformer writes out full dataset

### ISSUE THREAD

**Issue by williambrandler** [projectglow/glow#463]
The new quarantine functionality in the pipe transformer will successfully run if there are corrupted records, however, 

As an example, I created an input dataframe of 961 rows. 
The expected output dataframe count is 500 and the quarantine table is 461.
What I see is 500 and 961. It seems like all the data is piped out into the quarantine table.

See screenshots below. Code to reproduce can be found here https://github.com/projectglow/glow/pull/461

![Screen Shot 2021-12-14 at 11 53 08 AM](https://user-images.githubusercontent.com/51180067/146275468-ee076eb9-aa26-4e0f-bdd4-e30b39340ed9.png)
![Screen Shot 2021-12-14 at 11 55 37 AM](https://user-images.githubusercontent.com/51180067/146275470-0040cc87-f4e3-41df-94f1-e0a851b02978.png)

**Comment by mah-databricks** [comment]
issue verified. working on a fix.

**Comment by mah-databricks** [comment]
proving more complex than originally thought. Requires a rewrite of some of the internals of the Piper

**Comment by williambrandler** [comment]
c'est la vie!

ok, thanks for the update. 

How much effort do you think it will be?

**Comment by mah-databricks** [comment]
https://github.com/projectglow/glow/pull/469

**Comment by williambrandler** [comment]
thanks, this looks good
