### ISSUE TITLE
Improve handling of environment variables in the pipe transformer

### ISSUE THREAD

**Issue by Hoeze** [projectglow/glow#480]
From https://github.com/projectglow/glow/blob/master/docs/source/tertiary/pipe-transformer.rst:

> Options beginning with env_ are interpreted as environment variables. Like other options, the environment variable name is converted to lower snake case. For example, providing the option env_aniMal=MONKEY results in an environment variable with key ani_mal and value MONKEY being provided to the piped program.

Would it be possible to have some argument `jsonEnv` that can decode json-encoded environment variables?
E.g.:
```python
jsonEnv='{"PATH": "/usr/bin"}'
```
This would make it significantly easier to adjust environment variables IMHO.

**Comment by Hoeze** [comment]
The snake-case parsing of arguments makes it impossible to pass uppercase environment variables, right?
E.g. `env_TEST` would get translated to `t_e_s_t`.

Interestingly, passing `env_test_path='asdf'` results in an environment variable `test_path="asdf"`.
So actually there is no need to parse them as snake-case.

**Comment by williambrandler** [comment]
An alternative approach is to define environment variables via JSON and put those variables into your script, which is then run through the pipe transformer. Here is an example:

Here's an example
![Screen Shot 2022-02-01 at 1 28 36 PM](https://user-images.githubusercontent.com/51180067/152054431-43a22ce9-edca-480f-a9e5-db2c2aadceb6.png)
![Screen Shot 2022-02-01 at 1 28 27 PM](https://user-images.githubusercontent.com/51180067/152054435-bee554b2-4046-4365-b258-55d767e130aa.png)

Personally I have never used the environment variable feature in glow. Prefer the above approach

**Comment by Hoeze** [comment]
Ah, OK, I did not think of that solution :grin:

**Comment by williambrandler** [comment]
will keep the issue open for now until this is properly documented

should delete those environment variable options from the docs, they are somewhat confusing

**Comment by williambrandler** [comment]
updating the example in the docs to avoid this issue in future:

https://github.com/projectglow/glow/pull/490
