### ISSUE TITLE
Docker build.sh script is not current in tagged release

### ISSUE THREAD

**Issue by jebbd** [projectglow/glow#512]
Pulling the latest tagged release of glow (v 1.2.1), the docker files don't seem to be updated. Below shows the variables as in `build.sh` file in `docker/databricks/` 

```
DOCKER_HUB="projectglow"
DATABRICKS_RUNTIME_VERSION="9.1"
GLOW_VERSION="1.1.2"
HAIL_VERSION="0.2.85"
```

**Comment by williambrandler** [comment]
hey @jebbd, ah this is a consequence of the way the release process works, the release is first built and pushed, only then can a new docker container be built and tested, which goes in a subsequent pull request. Can you go from this pull request?

https://github.com/projectglow/glow/pull/509

which is where the tags were updated to the build script:
https://github.com/projectglow/glow/blob/master/docker/databricks/build.sh
