### ISSUE TITLE
Logistic regression ValueError: Null fit failed!

### ISSUE THREAD

**Issue by ConnorBarnhill** [projectglow/glow#527]
Hello,

When running the step 2 logistic regression I get an error: ValueError: Null fit failed!

This is the first time I've hit this error. I've gathered it's an error with the firth correction but how do I resolve?

Thanks,
Connor

**Comment by williambrandler** [comment]
Hey Connor, do you have any more information on the error?

Anything else you did differently from before?

**Comment by henrydavidge** [comment]
I think this is the same as #395
