### ISSUE TITLE
Spark version upgrade 3.4, 3.3

### ISSUE THREAD

**Issue by jisqaqov** [projectglow/glow#531]
Hello. Could you please tell me if any new release upcoming to support Glow with Spark 3.3 and 3.4 versions?

**Comment by zyd14** [comment]
Not a maintainer, but unfortunately it feels like this project has been mostly abandoned :(

**Comment by Hoeze** [comment]
See also https://github.com/projectglow/glow/issues/520.
I really love this library for its ability to read and write VCF files with pyspark, but I can imagine that glow itself has many features which are hard to maintain, e.g. the whole-genome regression things or the interop with hail.

**Comment by kermany** [comment]
100% agreed on the importance of the VCF parser and the need for making the project more maintainable by focusing on critical functionalities - e.g efficient ingest of VCF, bgen etc. stay tuned ...

**Comment by williambrandler** [comment]
@jisqaqov @zyd14 @Hoeze 

my understanding is that there is a version of glow on spark 3.4, but it hasn't been contributed back yet

@rlgarris can comment

**Comment by henrydavidge** [comment]
Hi @Hoeze @zyd14 @jisqaqov, we've now merged support for Spark 3.4 and 3.5. I'll release new artifacts soon. Until then, it's possible to test by building Scala and Python artifacts from source.

**Comment by doit-mattporter** [comment]
Is there an ETA for this new 3.4 + 3.5  support to be pushed to your Maven repo?
