### ISSUE TITLE
pip version not updated

### ISSUE THREAD

**Issue by jpdna** [projectglow/glow#60]
When I run:
```
 pip install glow.py
```
I get version 0.1.0
but the instructions at:
https://glow.readthedocs.io/en/latest/getting-started.html#running-locally
are looking for version 0.1.3
so those instructions don't work right now, says it can't find the dependency

**Comment by henrydavidge** [comment]
@jpdna most of our updates don't include Python changes, so we don't publish anything to pip. We can clarify this in our docs.
