### ISSUE TITLE
In lieu of Cannoli/ADAM/Avocado？

### ISSUE THREAD

**Issue by top1select** [projectglow/glow#69]
Hello,

It seems the major differences between Glow and Cannoli/ADAM/Avocado are Machine Learning orientated features with MLFlow plus Delta Lake.

So will Glow make Cannoli/ADAM/Avocado Pipeline obsolete down the road?

Thanks!

**Comment by henrydavidge** [comment]
@top1select here's my take:
1) When ADAM and friends began, people used Spark very differently than they do today. At the time, most Spark workflows used the RDD API. Today, the DataFrame / Dataset API is more common. We built Glow especially to fit into this usage pattern -- the Glow API is much more tightly integrated with Spark SQL.
2) Glow is primarily focused on variation data, while ADAM's feature set is read-data heavy. There is a lot more variation data today than there was when development started on ADAM :).

There are a lot of useful features in ADAM, again especially for working with read data, and there are plenty of people who use both. 

Hope that helps!
